### ISSUE TITLE
idea: Bucket values must be increasing - why throw?

### ISSUE THREAD

**Issue by a-h** [andrasm/prometheus-net#54] opened 2017-06-19 18:13 UTC
If there's a check to see whether the items are sorted or not, why not just apply a sort instead? 

```C#
throw new ArgumentException("Bucket values must be increasing");
````

**Comment by brian-brazil** [comment] 2017-09-22 08:35
If they're out of order the chances are that the user made a typo and should be alerted to that fact, as I'd expect ~everyone to attempt to provide them in order.

**Comment by sandersaares** [comment] 2018-01-24 08:48
Rationale above makes sense. Closing as by design.

**Closed by sandersaares** 2018-01-24 08:48 UTC
