### ISSUE TITLE
Idea: stop the collector from throwing an exception if the label format is not permitted

### ISSUE THREAD

**Issue by a-h** [andrasm/prometheus-net#53] opened 2017-06-19 17:44 UTC
Rather than doing that, which might happen at runtime rather than during unit testing, maybe it could clean the invalid characters out of the label names instead and maybe log a warning?

For example:

```c#
public class LabelCleaner
    {
        readonly static Regex LabelNameRegex = new Regex("[^a-zA-Z_:0-9]");

        public static string[] Clean(IEnumerable<string> labels)
        {
            return labels.Select(l => clean(l)).ToArray();
        }

        private static string clean(string label)
        {
            if (char.IsDigit(label.FirstOrDefault()))
            {
                return clean("l_" + label);
            }
            return LabelNameRegex.Replace(label, "_");
        }
    }
```

```c#
public class LabelCleanerTests
    {
        [Fact]
        public void SpacesAreReplaced()
        {
            Run(" ", "_");
        }

        [Fact]
        public void AmpersandsAreReplaced()
        {
            Run("&", "_");
        }

        [Fact]
        public void BracketsAreReplaced()
        {
            Run("{}", "__");
        }

        [Fact]
        public void ValidCharactersAreNotReplaced()
        {
            Run("this_is_valid", "this_is_valid");
        }

        [Fact]
        public void MustStartWithALetter()
        {
            Run("123_not_valid", "l_123_not_valid");
        }

        [Fact]
        public void EmptyLabelsDoNotThrowExceptions()
        {
            Run("", "");
        }

        public void Run(string input, string expected)
        {
            var result = LabelCleaner.Clean(new string[] { input });
            Assert.Equal(expected, result[0]);
        }
    }
```

**Comment by a-h** [comment] 2017-06-19 18:05
Also, the exception just says "Invalid label name!" rather than listing the label content.

**Comment by brian-brazil** [comment] 2017-09-22 08:34
I'd say that throwing an exception is correct. It's important that users provide valid label names.

**Comment by sandersaares** [comment] 2018-01-24 08:51
Indeed - you should be providing valid label names. I can understand there may be a need to "clean" if you get label names from some external source but that seems like a rather unusual design that does not make for a good primary use case for this library API.

Closing as by design. I will add the label name to the exception message, though, for easier diagnostics.

**Closed by sandersaares** 2018-01-24 08:51 UTC

**Comment by sandersaares** [comment] 2018-01-25 11:06
Label names have been added to exception messages in version 2.0. Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
