### ISSUE TITLE
Counter allows no way to reset to zero

### ISSUE THREAD

**Issue by godefroi** [andrasm/prometheus-net#63] opened 2017-10-27 22:48 UTC
Currently, the `Counter` class provides as its only way to alter the value the `Inc()` method. This method only takes values >= 0, which means that there is no way to reset the `Counter` and no way to decrement its value.

I am using the `Counter` class to mirror a value from a Windows performance counter, which acts as a counter. Because I have no way to interact with the `Counter` other than increment it, I am required to track each value that I retrieve from the performance counter, and compare it against each new sample, and do the math myself to determine how much it's incremented.

It's my understanding that the Prometheus server itself does this math. The documentation at https://prometheus.io/docs/instrumenting/writing_clientlibs/ allows client libraries to offer a method to reset Counter values to zero. I believe this would be a useful functionality, but it is not enough alone to eliminate the requirement for client code to maintain the previously sampled value and compare the current value.

**Comment by sandersaares** [comment] 2018-01-22 14:14
You can use a Gauge if you are simply mirroring an external counter. This will allow you to set the value directly without regard to its previous value.

Does this approach satisfy your use case?

**Comment by godefroi** [comment] 2018-01-23 15:43
The value I'm mirroring behaves like a counter, though. Using a GAUGE type would be misrepresenting what the underlying value is.

**Comment by sandersaares** [comment] 2018-01-24 09:24
The Prometheus metrics APIs are really meant to be viewed from the point of view of the thing being instrumented. Quoting [Prometheus docs](https://prometheus.io/docs/instrumenting/clientlibs/) with my emphasis:

> Before you can monitor your services, you need to add instrumentation to **their code** via one of the Prometheus client libraries.

If you are coyping metrics from some external non-Prometheus instrumentation (e.g. Windows performance counters or external services) you are no doubt going to run into concept/terminology mismatches.

The Counter API is designed for counting events occurring in your own code and this does not require any reset/set functionality. If you wish to preserve the "Counter" type in the wire format while still being able to arbitrarily set a value from an external source, you are best served by implementing a custom Collector.

Closing this as by design.

**Closed by sandersaares** 2018-01-24 09:24 UTC

**Comment by zscn** [comment] 2020-01-07 20:12
The official Prometheus doc mentioned it might be useful to create a reset function for [Counter](https://prometheus.io/docs/instrumenting/writing_clientlibs/#counter) 
> Counter is a monotonically increasing counter. It MUST NOT allow the value to decrease, however it MAY be reset to 0 (such as by server restart). 

is it worth to consider adding a reset function?

**Comment by devinbost** [comment] 2020-01-16 23:10
It really makes little sense to not be able to reset a counter...

**Comment by sandersaares** [comment] 2020-02-09 11:09
A counter is meant to count events that occur. A message comes in. Then one more. Then another. That makes 3 increments.

These events do not un-happen, so the value decreasing (whether to zero or not) seems like it would encourage some suspicious usage patterns.

What exactly is the usage that would benefit from a reset to zero?

The original poster describes translating from a different metrics format to Prometheus, which is not a design goal of this library. If your use case is different, please make your case and convince me that resetting a counter to zero is the right way to act when exporting your metric.

**Comment by sevencardz** [comment] 2020-04-03 01:23
Use Case: I want to count the number of requests that succeed or fail. I use a counter with two labels: {succeed, fail}. I want to be able to reset the counter back to 0 on demand. 

As a workaround to reset the counter, I unregister the counter, build a new one, and then register the new one. Here's some pseudocode:

```
// initialize counter
Counter.Builder requestCounterBuilder = Counter.build().name("request_counter").labelNames("outcome");
Counter requestCounter = requestCounterBuilder.register();

// capture metrics 
if(success)
    requestCounter.labels("success").inc();
else
    requestCounter.labels("failed").inc();

// reset counter
CollectorRegistry.defaultRegistry.unregister(requestCounter);
requestCounter = requestCounterBuilder.register();
```

**Comment by joeySchentrup** [comment] 2020-04-07 18:13
Use case: Unit testing. I have one unit test that runs incrementing the counter then would like to reset it to 0 for the next one. Really inconvenient to have to unregister the reregister it.

**Comment by kevinjqiu** [comment] 2020-07-15 22:10
To add to the conversation: A `ConterVec` has a `Reset()` method, while a `Counter` doesn't.  Just like @joeySchentrup we need Reset() in testing as well, and to get around that, we could just converted `Counter`s to `CounterVec`s but it feels wrong.

**Comment by alishah730** [comment] 2020-09-30 16:30
I need a daily request counter.
lets assume till 11:59:00hrs my counter value is 560 on a particular day
but I want at 00:00:01 next day the counter should be set to 0.

any idea?
can I not direct do something  like

`Request_Counter.reset();`
or 
`Request_Counter.set(0);`

**Comment by sandersaares** [comment] 2020-10-18 12:20
Data analytics like "daily requests" are better handled on a layer above prometheus-net. This library is designed for instrumenting your app and exporting the raw data. Queries and post-processing of the data in the Prometheus database can create views like daily aggregates.

As for unit testing, the standard pattern is to use a new collector registry for each test.

**Comment by desincarnage** [comment] 2021-01-05 01:30
Use case: I want to monitor my monthly network bandwidth usage so I can get alerts when I get close to a certain threshold. Right now, I have to do a workaround using a gauge and add the increase of my router's WAN port ingress and egress traffic over the time elapsed this month so far. 
Unfortunately, the results are unreliable, because the values differ depending on if I'm looking at the whole month (with empty data for future days) or at only the days elapsed this month so far.

If counters could be reset, I could just schedule a reset to 0 on the first second of each month and count from there.

**Comment by Samreay** [comment] 2021-08-10 15:13
Stumbled across this whilst trying to make unit testing work and adding another `+1`

This seems quite a simple use case:

1. You have a counter that counts exceptions
2. You have a test which does not except, and want to ensure the counter value remains zero.
3. You have a test which deliberately errors, and want to ensure the counter has incremented properly.

This makes having a method which runs prior to each test that resets the metrics super useful.

Is there anything like this available? 

@sandersaares I assume you've seen people integrate prometheus into their testing, is there a better pattern or solution that you'd recommend?

**Comment by hmiguel** [comment] 2022-08-10 09:18
I facing the same issue trying to implement integration tests to check metric values. At the moment I'm unable to clear the metrics before each test. Very annoying.

**Comment by Svendelmaus** [comment] 2023-02-07 02:01
I have a quota of data I can use, which is renewed once a year.

I want to track a Counter of the data I have used -- particularly because I want to monitor the rate of change, so I can set up checks to warn if I see unusual increases in usage. (I'll also have alerts when I have used X% of my quota, but that's not something I need a Counter for.)

When the year rolls around, I want to set the Counter back to zero, since at that point I won't have used any of that year's quota of data.

This seems to exactly match the use-case outlined in the Prometheus documentation -- a number that only increases, unless it resets.
